services:
  - type: web
    name: piedade-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: 86400000
      - key: PORT
        value: 8888
